language: node_js
node_js:
- "node"
script:
- yarn test
- yarn lint
deploy:
  - provider: npm
    email: benedict@hearthsim.net
    api_key:
      secure: gVYNyDHMXz47vvGu2ve8pMorSJMG6Bq3AiOLm1ZUubLaB5MzyFPpKhBor/ETA18vlNXL/PahyGXZjrqiaGi5+BmtYsc4R91CukOmRpzErgYzJ3JldteV0DcyrkX3akL6KXPHEhlOMqkr6kcgZj+QsvvxfybikuNH9UedEl1z5L06dlOVgoEzFcP3x7fOExtZ0AurLFnTbqSRkpj7a8Bj+GE/f6BNrT3j+YgBdNL9sCsuxLuDYvoYUQJuHyCNduztssBeCAKkYCgm/Rf2Yh3DUe33sG2gkXaArHl0ZePf97zFEy6NdlTgcsjLp77UNDcgkvU+bOxDfOqQ/OBkpSwCAax7BkIbbEekT26LdMF17f0bLx+FA8VX0rS1L0hBqLpeCumQR8AhXQRxuNokZ/azOeWDteGG8ZRDrzBV/H8O5zZMZtAjHA3L8yNwBQApYSNiitGahIY2geWxzf55l18Ekgs3n+ISC/GPIEyAebIxcdn/7jI7djslsVrK0At7lo5PBMTMwRoOT5MHRnL9EMR+9UrYLu3INKINCvOsOjfRy8wDbYK3Rd82thyFJhlK7KYnrcGpHZNTZoV6CDNDXPTwKG42GgQ2/zOwiHXxMVI3GTmTh4ByRQkLZQRz3jn7PLtM2SHtvvySe+R1oiI4r8g0S3uFq1qKYi4Cnsk9NJaTwN8=
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: releases
    api_key:
      secure: grwqEV6OSMKZJUP+2Qkzslad2xbuDm36G/8rwj7FaF6M3mdWQS+CrbpM8qrO/gjgylmJumwDU+WuuS13aL+WzC4fYSI1exX4bWzlr8x+8hM1TexFOYnQ1I8ejSB+kQnSHdwDnEzE+C4PpRB6VZU53Yh181vfVqxzHQAvUpFzZv2lyhagzESItJuONxPMtZgdmlrB44hWSseRmsfTAghhmTOMhl3YbTQ9fPF5wk6ICi0X7OoG1Sk8+ankXQWGYuoHMGBHz2Q35/kMvpBCIjRj0P4X6r2txNiz+llSDYMNfZ1PSGwcUWqQLGcLz0WXZA6sMMXtjN9PbRNJepgm7NTRf71X+nvpsFFxmYta1/LcftlnJ2wlTSZkXu7Rc+Ujd9zrPDcQFKnmWVMsw2N8k9/zKkBNjNh8oXAQfujI/bNryv7VQ3YznRz5Vh8+kd+UvTC/wCeYCX0Vt7ZHDvu0AVMCdsXJn4uDJub0Awra+r+Ft/BcibjGQekbFIoxG6i9cYuf+S62SqfTvT/8ypSjtJyNlo5bKYM8Vrzh4NoBPHl0AjomszviLzxYkRcCNcobqPonDmvqEBWNm5Df0waf4g6gNB7N/4KQrPLjHeyJXcr0POzel58vZR8RZ3xf1oGw5KjN5Npw445wSV/tBW+MMBQjkzVXuo+TuMgCBnjrgmFKFRU=
    file: lib/deckstrings.js
    skip_cleanup: true
    on:
      tags: true
      repo: HearthSim/npm-deckstrings
cache:
  yarn: true
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    channels:
    - chat.freenode.net#hearthsim-commits
    use_notice: true
    skip_join: true
    on_failure: always
    on_success: change
    template:
    - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
