language: node_js

node_js:
- "node"

cache:
  yarn: true

script: yarn run $SCRIPT

stages:
  - name: test
  - name: release
    if: tag =~ ^v\d

jobs:
  include:
      - env: SCRIPT=lint
      - env: SCRIPT=type-check
      - env: SCRIPT=build
      - env: SCRIPT=test:mocha
        script:
          - yarn run build
          - yarn run $SCRIPT
      - env: SCRIPT=test:karma
        sudo: true
        addons:
          chrome: stable
        script:
          - yarn run build
          - yarn run $SCRIPT
      - stage: release
        script: true
        deploy:
          - provider: npm
            email: $NPM_EMAIL
            api_key: $NPM_AUTH_TOKEN
            skip_cleanup: true
            on:
              tags: true
              branch: master
